---
- name: Create monitoring directory
  file:
    path: /home/{{ ansible_user }}/monitoring
    state: directory
    mode: '0755'

- name: Create Prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: /home/{{ ansible_user }}/monitoring/prometheus.yml
    mode: '0644'

- name: Create docker-compose for monitoring stack
  template:
    src: docker-compose-monitoring.yml.j2
    dest: /home/{{ ansible_user }}/monitoring/docker-compose.yml
    mode: '0644'
  notify: Start monitoring stack

- name: Create Grafana dashboard provisioning
  file:
    path: /home/{{ ansible_user }}/monitoring/grafana/provisioning/dashboards
    state: directory
    mode: '0755'
    recurse: yes

- name: Create Grafana datasource provisioning
  file:
    path: /home/{{ ansible_user }}/monitoring/grafana/provisioning/datasources
    state: directory
    mode: '0755'
    recurse: yes

- name: Copy Grafana datasource configuration
  template:
    src: datasource.yml.j2
    dest: /home/{{ ansible_user }}/monitoring/grafana/provisioning/datasources/datasource.yml
    mode: '0644'

- name: Copy Grafana dashboard configuration
  template:
    src: dashboard.yml.j2
    dest: /home/{{ ansible_user }}/monitoring/grafana/provisioning/dashboards/dashboard.yml
    mode: '0644'

- name: Copy Grafana dashboard
  template:
    src: node-exporter-dashboard.json.j2
    dest: /home/{{ ansible_user }}/monitoring/grafana/dashboards/node-exporter-dashboard.json
    mode: '0644'
