---
all:
  children:
    aws:
      hosts:
        aws_instance:
          ansible_host: "{{ aws_public_ip }}"
    ibm:
      hosts:
        ibm_instance:
          ansible_host: "{{ ibm_floating_ip }}"
vars:
  ansible_user: ubuntu
  ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  ansible_python_interpreter: /usr/bin/python3
