name: Deploy Paper.Social

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: |
        cd app
        npm install
    - name: Run tests
      run: |
        cd app
        npm test

  terraform:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      run: |
        cd terraform
        terraform fmt -check

    - name: Terraform Init
      run: |
        cd terraform
        terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        IC_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}

    - name: Terraform Validate
      run: |
        cd terraform
        terraform validate

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      run: |
        cd terraform
        terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        IC_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        cd terraform
        terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        IC_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}

    - name: Save Terraform Output
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        cd terraform
        terraform output -json > ../terraform-output.json

    - name: Upload Terraform Output
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: terraform-output
        path: terraform-output.json

  ansible:
    needs: terraform
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      id-token: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Download Terraform Output
      uses: actions/download-artifact@v4
      with:
        name: terraform-output

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

    - name: Generate Ansible Inventory
      run: |
        python -c '
        import json
        import os

        with open("terraform-output.json", "r") as f:
            tf_output = json.load(f)

        with open("ansible/inventory/hosts.yml", "w") as f:
            f.write("""---
        all:
          children:
            aws:
              hosts:
                aws_instance:
                  ansible_host: {}
            ibm:
              hosts:
                ibm_instance:
                  ansible_host: {}
          vars:
            ansible_user: ubuntu
            ansible_ssh_private_key_file: ~/.ssh/id_rsa
            ansible_python_interpreter: /usr/bin/python3
        """.format(
                tf_output["aws_public_ip"]["value"],
                tf_output["ibm_floating_ip"]["value"]
            ))
        '

    - name: Run Ansible Playbook
      run: |
        cd ansible
        ansible-playbook -i inventory/hosts.yml site.yml
