name: Deploy Paper.Social

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: |
        cd app
        npm install
    - name: Run tests
      run: |
        cd app
        npm test

  terraform:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Format Terraform files
      run: |
        cd terraform
        terraform fmt

    - name: Terraform Init
      run: |
        cd terraform
        terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        IC_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}

    - name: Terraform Validate
      run: |
        cd terraform
        terraform validate

    - name: Mock Terraform Output
      run: |
        cat > terraform-output.json << 'EOJSON'
        {
          "aws_instance_id": {
            "value": "i-mock12345"
          },
          "aws_public_ip": {
            "value": "192.168.1.10"
          },
          "aws_public_dns": {
            "value": "ec2-192-168-1-10.us-east-1.compute.amazonaws.com"
          },
          "ibm_instance_id": {
            "value": "ibm-mock67890"
          },
          "ibm_floating_ip": {
            "value": "192.168.2.20"
          }
        }
        EOJSON

    - name: Generate SSH Key for Artifacts
      run: |
        ssh-keygen -t rsa -b 4096 -f id_rsa -N ""

    - name: Upload Terraform Output
      uses: actions/upload-artifact@v4
      with:
        name: terraform-output
        path: terraform-output.json

    - name: Upload SSH Key
      uses: actions/upload-artifact@v4
      with:
        name: ssh-key
        path: id_rsa

  ansible:
    needs: terraform
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      id-token: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Download Terraform Output
      uses: actions/download-artifact@v4
      with:
        name: terraform-output

    - name: Download SSH Key
      uses: actions/download-artifact@v4
      with:
        name: ssh-key

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        mv id_rsa ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    - name: Generate Ansible Inventory
      run: |
        python -c '
        import json
        import os

        with open("terraform-output.json", "r") as f:
            tf_output = json.load(f)

        with open("ansible/inventory/hosts.yml", "w") as f:
            f.write("""---
        all:
          children:
            aws:
              hosts:
                aws_instance:
                  ansible_host: {}
                  ansible_connection: local # Mock connection for demo
            ibm:
              hosts:
                ibm_instance:
                  ansible_host: {}
                  ansible_connection: local # Mock connection for demo
          vars:
            ansible_user: ubuntu
            ansible_ssh_private_key_file: ~/.ssh/id_rsa
            ansible_python_interpreter: /usr/bin/python3
        """.format(
                tf_output["aws_public_ip"]["value"],
                tf_output["ibm_floating_ip"]["value"]
            ))
        '

    # Instead of actual deployment, show what would happen
    - name: Show Ansible Inventory and Execution Plan
      run: |
        echo "======= ANSIBLE INVENTORY ======="
        cat ansible/inventory/hosts.yml
        echo ""
        echo "======= EXECUTION PLAN ======="
        echo "1. Ansible would install Docker on AWS and IBM instances"
        echo "2. Ansible would deploy Paper.Social web app to both clouds"
        echo "3. Ansible would configure Prometheus + Grafana monitoring"
        echo ""
        echo "In a real deployment with proper cloud credentials:"
        echo "- Web app would be available at: http://AWS_IP and http://IBM_IP"
        echo "- Monitoring would be accessible at: http://AWS_IP:3000 and http://IBM_IP:3000"
