name: Deploy Paper.Social

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: |
        cd app
        npm install
    - name: Run tests
      run: |
        cd app
        npm test

  aws_deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Format Terraform files
      run: |
        cd terraform
        terraform fmt

    - name: Terraform Init
      run: |
        cd terraform
        terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Validate
      run: |
        cd terraform
        terraform validate

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        cd terraform
        terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Save Terraform Output
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        cd terraform
        # Create output file manually to ensure proper format
        echo '{
          "aws_instance_id": {
            "value": "'$(terraform output -raw aws_instance_id)'"
          },
          "aws_public_ip": {
            "value": "'$(terraform output -raw aws_public_ip)'"
          },
          "aws_public_dns": {
            "value": "'$(terraform output -raw aws_public_dns)'"
          },
          "ibm_instance_id": {
            "value": "ibm-mock-instance"
          },
          "ibm_floating_ip": {
            "value": "192.168.2.20"
          }
        }' > ../terraform-output.json
        cp id_rsa ../id_rsa

    - name: Upload Terraform Output
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: terraform-output
        path: terraform-output.json

    - name: Upload SSH Key
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: ssh-key
        path: id_rsa

  ansible:
    needs: aws_deploy
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      id-token: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible
        
    - name: Download Terraform Output
      uses: actions/download-artifact@v4
      with:
        name: terraform-output
        
    - name: Download SSH Key
      uses: actions/download-artifact@v4
      with:
        name: ssh-key
        
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        mv id_rsa ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        
    - name: Generate Ansible Inventory
      run: |
        cat terraform-output.json
        # Create inventory directly without parsing JSON
        cat > ansible/inventory/hosts.yml << 'EOL'
        ---
        all:
          children:
            aws:
              hosts:
                aws_instance:
                  ansible_host: $(grep -o '"aws_public_ip".*"value": *"[^"]*"' terraform-output.json | grep -o '"value": *"[^"]*"' | grep -o '"[^"]*"$' | tr -d '"')
            ibm:
              hosts:
                ibm_instance:
                  ansible_host: 192.168.2.20
                  ansible_connection: local  # Mock connection for IBM
          vars:
            ansible_user: ubuntu
            ansible_ssh_private_key_file: ~/.ssh/id_rsa
            ansible_python_interpreter: /usr/bin/python3
            ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        EOL
        cat ansible/inventory/hosts.yml

    - name: Wait for AWS SSH connectivity
      run: |
        # Get AWS IP address from inventory file
        AWS_IP=$(grep -o "ansible_host: .*" ansible/inventory/hosts.yml | head -1 | awk '{print $2}')
        echo "AWS IP: $AWS_IP"
        
        # Only proceed with SSH check if we have a real IP
        if [[ $AWS_IP != "192.168."* ]]; then
          for i in {1..20}; do
            echo "Attempt $i: Connecting to $AWS_IP..."
            if ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -i ~/.ssh/id_rsa ubuntu@$AWS_IP 'exit' 2>/dev/null; then
              echo "Successfully connected to AWS instance"
              break
            fi
            echo "Failed to connect, retrying in 15 seconds..."
            sleep 15
            if [ $i -eq 20 ]; then
              echo "Could not establish SSH connection to AWS instance"
              exit 1
            fi
          done
        else
          echo "Using mock IP, skipping SSH connectivity check"
        fi

    - name: Run Ansible Playbook
      run: |
        cd ansible
        ansible-playbook -i inventory/hosts.yml site.yml -v
